spring.application.name=v-mall
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/vmall?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456789
#
spring.jpa.hibernate.ddl-auto=update
##spring.datasource.initialization-mode=always
spring.jpa.show-sql=true
#jwt.secret-key=TXlTdXBlclNlY3JldEtleUZvckpXVFRva2VuU3ByaW5nQm9vdDIwMjY=
#jwt.expiration=86400000
#
#application.mailing.frontend.activation-url=http://localhost:8080/auth/activate-account
#
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#
#spring.mail.username=mohamedsayed33333333@gmail.com
#spring.mail.password=dyfd aowu grpu arlt
#
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## Google
#spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
#spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
#
#
## GITHUB
#
#spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
#spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
#
